---
cluster:
  type: k3s
  name: demos-cluster
  nodes: 2
  node_type: g4s.kube.large
  cni: cilium
  label-nodes: mainpool
  region: LON1
firewall:
  name: demos-firewall
extra-nodepool:
  nodes: 1
  node_type: g4s.kube.small
