---
cluster:
  type: k3s
  name: demo-cluster
  nodes: 3
  kubernetes_version: 1.24.4-k3s1
  node_type: g4s.kube.medium
  cni: cilium
  label-nodes: demos-first-pool
  region: LON1
firewall:
  name: demo-firewall
