---
cluster:
  type: k3s
  name: demo-cluster
  nodes: 3
  node_type: g4s.kube.medium
  cni: cilium
  label-nodes: demos-first-pool
  region: LON1
  applications: "traefik"
firewall:
  name: demo-firewall
