---
name: "Deploy Terraform Infrastructure"

on: #yamllint disable-line rule:truthy
  push:
    branches:
      - master

env:
  # Credentials for deployment to CIVO
  TF_VAR_civo_token: ${{ secrets.CIVO_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the infra directory.
        working-directory: ./infra

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init -upgrade

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Move kubeconfig
        run: |
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest" # default is latest stable
        id: install

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest" # default is latest stable
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Add ArgoCD repo
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install ArgoCD
        run: |
          helm upgrade --install argocd argo/argo-cd \
          --create-namespace --version 5.39.0 -f argo-chart/values.yaml \
          --wait --timeout 5m0s -n argocd

      - name: Install Argo application
        working-directory: ./argo-app
        run: |
          kubectl apply -f . --recursive

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
